### ISSUE TITLE
ArduinoSound Library support

### ISSUE THREAD

**Issue by VojtechBartoska** [espressif/arduino-esp32#6231]
This issue tracks adding support of [ArduinoSound Library](https://www.arduino.cc/en/Reference/ArduinoSound)  with use of I2S implementation.

- [ ] decide if the implementation is worthy

---
**Tasks breakdown:**
- [ ] add LyraT Support
- [x] Cut down to most basic compatibility (FFT)
- [ ] Verify clear audio input and output on all possible settings (see [notes](https://docs.google.com/document/d/1-OGWEkIzBJa1a2e-nqYA2eN_V8vU3lXJIYmvDUM3sac/edit?usp=sharing))
  - [ ] I2S
  - [ ] ADC/DAC
  - [ ] PDM

Basic implementation:
- [ArduinoSound personal repo](https://github.com/PilnyTomas/ArduinoSound/tree/separate_i2s)

**Comment by pschatzmann** [comment]
How about just using the [Audio Tools Library](https://github.com/pschatzmann/arduino-audio-tools). It supports plenty of audio devices including the LyraT
